[package]
name = "guest-rust"
version = "0.1.0"
edition = "2021"
authors = ["Darwin Boersma <darwin@sadlark.com>"]
description = ""

[lib]
crate-type = [ "cdylib" ]

[dependencies]
spin-sdk = "3.0"
spin-kinesis-sdk = { path = "../sdk"}

[workspace]
