spin_manifest_version = 2

[application]
name = "guest_rust"
version = "0.1.0"
authors = ["Darwin Boersma <darwin@sadlark.com>"]
description = ""

[[trigger.kinesis]]
component = "guest-rust"
stream_arn = "arn:aws:kinesis:us-east-1:123456789012:stream/TestStream"
batch_size = 10
shard_idle_wait_millis = 1000
detector_poll_millis = 30000
shard_iterator_type = "LATEST"

[component.guest-rust]
source = "target/wasm32-wasi/release/guest_rust.wasm"
allowed_outbound_hosts = []
[component.guest-rust.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
