spin_manifest_version = 2

[application]
name = "{{project-name}}"
authors = ["{{authors}}"]
description = "{{project-description}}"
version = "0.1.0"

[[trigger.kinesis]]
component = "{{project-name | kebab_case}}"
stream_arn = "{{stream-arn}}"
batch_size = {{batch-size}}
shard_idle_wait_millis = {{shard-idle-wait-millis}}
detector_poll_millis = {{detector-poll-millis}}
shard_iterator_type = "{{shard-iterator-type}}"

[component.{{project-name | kebab_case}}]
source = "target/wasm32-wasi/release/{{project-name | snake_case}}.wasm"
[component.{{project-name | kebab_case}}.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
